#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use TennisGame\Command\TennisGameCommand;

$application = new Application();
$application->add(new TennisGameCommand());
$application->run();
